package com.example.apppedido.domain.Model

import com.example.appcomandav20.data.source.remote.dto.DetalleDTO
import com.example.appcomandav20.data.source.remote.dto.SendOrdersDTO


data class SendOrdersModel(
    val iD_PEDIDO: Int,
    val numerO_PEDIDO: String,
    val noM_MON: String,
    val smB_MON: String,
    val conD_PAGO: String,
    val persona: String,
    val ruc: String,
    val freC_DIAS: String,
    val codigO_VENDEDOR: String,
    val codigO_CPAGO: String,
    val codigO_MONEDA: String,
    val fechA_PEDIDO: String,
    val numerO_OCLIENTE: String,
    val importE_STOT: Double,
    val importE_IGV: Double,
    val importE_DESCUENTO: Int,
    val importE_TOTAL: Double,
    val porcentajE_DESCUENTO: Int,
    val porcentajE_IGV: Int,
    val observacion: String,
    val serie: String,
    val estado: String,
    val iD_CLIENTE: Int,
    val importE_ISC: Int,
    val usuariO_CREACION: String,
    val usuariO_AUTORIZA: String,
    val fechA_CREACION: String,
    val fechA_MODIFICACION: String,
    val codigO_EMPRESA: String,
    val codigO_SUCURSAL: String,
    val valoR_VENTA: Double,
    val iD_CLIENTE_FACTURA: Int,
    val codigO_VENDEDOR_ASIGNADO: String,
    val fechA_PROGRAMADA: String,
    val facturA_ADELANTADA: String,
    val contacto: String,
    val emaiL_CONTACTO: String,
    val lugaR_ENTREGA: String,
    val iD_COTIZACION: Int,
    val comision: Int,
    val puntO_VENTA: String,
    val redondeo: String,
    val validez: String,
    val motivo: String,
    val correlativo: String,
    val centrO_COSTO: String,
    val tipO_CAMBIO: Int,
    val sucursal: String,
    val mesa: String,
    val piso: String,
    val detalle: List<DetalleModel>
)

data class DetalleModel(
    val iD_PEDIDO: Int,
    val iD_PRODUCTO: Int,
    val cantidad: Int,
    val nombre: String,
    val precio: Double,
    val descuento: Int,
    val igv: Double,
    val importe: Double,
    val canT_DESPACHADA: Int,
    val canT_FACTURADA: Int,
    val observacion: String,
    val secuencia: Int,
    val preciO_ORIGINAL: Double,
    val tipo: String,
    val importE_DSCTO: Int,
    val afectO_IGV: String,
    val comision: Int,
    val iD_PRESUPUESTO: Int,
    val cdG_SERV: String,
    val flaG_C: String,
    val flaG_P: String,
    val flaG_COLOR: String,
    val noM_UNIDAD: String,
    val comanda: String,
    val mozo: String,
    val unidad: String,
    val codigO_BARRA: String,
    val poR_PERCEPCION: Int,
    val percepcion: Int,
    val valoR_VEN: Double,
    val uniD_VEN: String,
    val fechA_VEN: String,
    val factoR_CONVERSION: Int,
    val cdG_KIT: String,
    val swT_PIGV: String,
    val swT_PROM: String,
    val canT_KIT: Int,
    val swT_DCOM: String,
    val swT_SABOR: String,
    val swT_FREE: String,
    val noM_IMP: String,
    val seC_PROD: Int,
    val poR_DETRACCION: Int,
    val detraccion: Int,
    val usuariO_ANULA: String,
    val fechA_ANULA: String,
    val margen: Int,
    val importE_MARGEN: Int,
    val costO_ADIC: Int
)

fun SendOrdersModel.toSendOrdersDTO(): SendOrdersDTO {

    val dato = detalle.mapIndexed { _, entries ->

        DetalleDTO(
            iD_PEDIDO = entries.iD_PEDIDO,
            iD_PRODUCTO = entries.iD_PRODUCTO,
            cantidad= entries.cantidad,
            nombre= entries.nombre,
            precio= entries.precio,
            descuento= entries.descuento,
            igv= entries.igv,
            importe= entries.importe,
            canT_DESPACHADA= entries.canT_DESPACHADA,
            canT_FACTURADA= entries.canT_FACTURADA,
            observacion= entries.observacion,
            secuencia= entries.secuencia,
            preciO_ORIGINAL= entries.preciO_ORIGINAL,
            tipo= entries.tipo,
            importE_DSCTO= entries.importE_DSCTO,
            afectO_IGV= entries.afectO_IGV,
            comision= entries.comision,
            iD_PRESUPUESTO= entries.iD_PRESUPUESTO,
            cdG_SERV= entries.cdG_SERV,
            flaG_C= entries.flaG_C,
            flaG_P= entries.flaG_P,
            flaG_COLOR= entries.flaG_COLOR,
            noM_UNIDAD= entries.noM_UNIDAD,
            comanda= entries.comanda,
            mozo= entries.mozo,
            unidad= entries.unidad,
            codigO_BARRA= entries.codigO_BARRA,
            poR_PERCEPCION= entries.poR_PERCEPCION,
            percepcion= entries.percepcion,
            valoR_VEN= entries.valoR_VEN,
            uniD_VEN= entries.uniD_VEN,
            fechA_VEN= entries.fechA_VEN,
            factoR_CONVERSION= entries.factoR_CONVERSION,
            cdG_KIT= entries.cdG_KIT,
            swT_PIGV= entries.swT_PIGV,
            swT_PROM= entries.swT_PROM,
            canT_KIT= entries.canT_KIT,
            swT_DCOM= entries.swT_DCOM,
            swT_SABOR= entries.swT_SABOR,
            swT_FREE= entries.swT_FREE,
            noM_IMP= entries.noM_IMP,
            seC_PROD= entries.seC_PROD,
            poR_DETRACCION= entries.poR_DETRACCION,
            detraccion= entries.detraccion,
            usuariO_ANULA= entries.usuariO_ANULA,
            fechA_ANULA= entries.fechA_ANULA,
            margen= entries.margen,
            importE_MARGEN= entries.importE_MARGEN,
            costO_ADIC= entries.costO_ADIC
        )
    }

    return  SendOrdersDTO(
    iD_PEDIDO = iD_PEDIDO,
    numerO_PEDIDO = numerO_PEDIDO,
    noM_MON = noM_MON,
    smB_MON = smB_MON,
    conD_PAGO = conD_PAGO,
    persona = persona,
    ruc = ruc,
    freC_DIAS = freC_DIAS,
    codigO_VENDEDOR = codigO_VENDEDOR,
    codigO_CPAGO = codigO_CPAGO,
    codigO_MONEDA = codigO_MONEDA,
    fechA_PEDIDO = fechA_PEDIDO,
    numerO_OCLIENTE = numerO_OCLIENTE,
    importE_STOT = importE_STOT,
    importE_IGV = importE_IGV,
    importE_DESCUENTO = importE_DESCUENTO,
    importE_TOTAL = importE_TOTAL,
    porcentajE_DESCUENTO = porcentajE_DESCUENTO,
    porcentajE_IGV = porcentajE_IGV,
    observacion = observacion,
    serie = serie,
    estado = estado,
    iD_CLIENTE = iD_CLIENTE,
    importE_ISC = importE_ISC,
    usuariO_CREACION = usuariO_CREACION,
    usuariO_AUTORIZA = usuariO_AUTORIZA,
    fechA_CREACION = fechA_CREACION,
    fechA_MODIFICACION = fechA_MODIFICACION,
    codigO_EMPRESA = codigO_EMPRESA,
    codigO_SUCURSAL = codigO_SUCURSAL,
    valoR_VENTA = valoR_VENTA,
    iD_CLIENTE_FACTURA = iD_CLIENTE_FACTURA,
    codigO_VENDEDOR_ASIGNADO = codigO_VENDEDOR_ASIGNADO,
    fechA_PROGRAMADA = fechA_PROGRAMADA,
    facturA_ADELANTADA = facturA_ADELANTADA,
    contacto = contacto,
    emaiL_CONTACTO = emaiL_CONTACTO,
    lugaR_ENTREGA = lugaR_ENTREGA,
    iD_COTIZACION = iD_COTIZACION,
    comision = comision,
    puntO_VENTA = puntO_VENTA,
    redondeo = redondeo,
    validez = validez,
    motivo = motivo,
    correlativo = correlativo,
    centrO_COSTO = centrO_COSTO,
    tipO_CAMBIO = tipO_CAMBIO,
    sucursal = sucursal,
    mesa = mesa,
    piso = piso,
    detalle = dato
    )
}
